//
//
//
// DB
import 'package:cloud_firestore/cloud_firestore.dart';

const String kdb_quizs = 'quizs';
const String kdb_subjects = 'subjects';
const String kdb_languages = 'languages';
const String kdb_gallery = 'gallery';
const String kdb_languageCode = 'languageCode';
const String kdb_languageName = 'languageName';
const String kdb_isPublic = 'isPublic';
const String kdb_label = 'label';
const String kdb_sortDesc = 'sortDesc';
const String kdb_imageUrl = 'imageUrl';
const String kdb_isProVersion = 'isProVersion';
const String kdb_id = 'id';
const String kdb_subjectId = 'subjectId';
const String kdb_question = 'question';
const String kdb_hint = 'hint';
const String kdb_explain = 'explain';
const String kdb_answers = 'answers';
const String kdb_index = 'index';
const String kdb_value = 'value';
const String kdb_isCorrect = 'isCorrect';
const String kdb_isForKid = 'isForKid';
const String kdb_questions = 'questions';
const String kdb_mime = 'mime';
const String kdb_url = 'url';
const String kdb_path = 'path';
const String kdb_size = 'size';
const String kdb_fileName = 'fileName';
const String kdb_configs = 'configs';
const String kdb_live = 'live';
const String kdb_token = 'token';
const String kdb_appId = 'appId';
const String kdb_channelId = 'channelId';
const String kdb_comment = 'comment';
const String kdb_note = 'note';
const String kdb_isEnable = 'isEnable';
const String kdb_status = 'status';
const String kdb_waiting = 'waiting';
const String kdb_preparing = 'preparing';
const String kdb_streaming = 'steaming';
const String kdb_countViewer = 'countViewer';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = '';
// const String kdb_ = ''; 
